### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [jniedballa/camtrapR#22]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by jniedballa** [comment]
Solved in 3a5e0ebb79cd82f639806fba8ac661b7fa7c44c8, ad1b0e35c6fe19fbabcf4b6da6119fb3350ef475, 9eceab49be39afde57d31d7c859d27d8368c8a3b, and 820ce4b311116b5b4c5880f9ebb0fa1f53829e58.
CRAN submission will follow soon
