### ISSUE TITLE
Adding .mp4 compatibility to imageRename function

### ISSUE THREAD

**Issue by bjbarrett** [jniedballa/camtrapR#9]
Are there any plans to add video (i.e. .mp4) compatability to the imageRename function? 

Reconyx Ultrafires have readable dates where the file was created, that are extractable with exiftool. It looks to be stored in the "File"  tag group in the 'FileModifyDate' metadata (time zone relative to the computer). Under the QuickTime meta data tag_group 'CreateDate' it has a time zone relative to the camera.

Perhaps forcing the user to specify what metadata to read dates + times from will help avoid and incorrect dating schemes that occur when files are moved and the file access date changes.

![image](https://user-images.githubusercontent.com/12502932/87419167-4daa5000-c5d3-11ea-931e-8b23fa4de2c1.png)

**Comment by jniedballa** [comment]
Added in 86a85d04199d47c902979e23a7daf0e062d9889a.  Parameter "video" works the same as in recordTable.
